### ISSUE TITLE
Non-sequential Index id's Lost After Save

### ISSUE THREAD

**Issue by puregame** [spotify/annoy#279]
See attached screenshot for an example of the error. 

<img width="1102" alt="screen shot 2018-02-13 at 10 44 04 pm" src="https://user-images.githubusercontent.com/6061458/36186836-851fead4-110f-11e8-9552-9a0c1dd3af71.png">

The behavior is the same for an index loaded from disk. 

Is this expected behavior or a bug? As per the documentation `i` can be any non-negative integer, there is no stated restriction on if id's must be sequential.

**Comment by erikbern** [comment]
This seems like a bug, no idea why it behaves like that.

Let me try to reproduce

**Comment by erikbern** [comment]
i can reproduce this

**Comment by erikbern** [comment]
figured out what's going on – when load()ing, annoy is confusing the number of nodes with the maximum number of nodes. i'm actually not quite sure how to fix this without doing something weird like scanning through the whole index. seems a bit unfortunate.

**Comment by erikbern** [comment]
There's a simple/dumb solution – just do binary search to find the largest id with a vector associated with it. I'll hack something together tonight.

This is an unfortunate consequence of my attempt to always keep Annoy indexes indefinitely backwards compatible. At some point I'm tempted to drop the compatibility and redefine the binary format.

**Comment by puregame** [comment]
Is it safe to say that searching affected indexes by vector will be unaffected?

Based on some small tests it seems as though searching these indexes by a vector returns the correct id's.

**Comment by erikbern** [comment]
Yeah the only issue is that the number of items in the index will be underestimated. Everything else should work

**Comment by peterldowns** [comment]
@erikbern just wanted to thank you for the clear writeup and responses to this issue -- just ran into it myself. I can confirm that when querying by vector, the returned results still have the correct item numbers, it's just that I can't use them in a search.

```python
index.get_n_items() # 1200
doc.id # 1798
index.get_item_vector(1798) # IndexError: Item index larger than the largest item index
index.get_nns_by_vector(d.get_vector(), 1, search_k=1000) # [1798]
```

In my system, not every document has a vector, and I'm serving queries using workers that call `index.load()` to refer to a pre-computed index. So for now I'm working around the problem by only allowing querying by vector rather than document ID, which is obviously slightly more of a pain but still workable. I would greatly appreciate if this would be fixed. If I can figure out the code and fix it myself I will send a PR but I'm no C++ expert, please don't count on it.

**Comment by erikbern** [comment]
hm interesting. as a workaround maybe you can insert "dummy" vectors (with all zeros) or something similar for now

**Comment by peterldowns** [comment]
Not a bad idea, but querying by vector isn't that painful -- everywhere I want to find related documents I have both the document ID and the document vector available. And then I'd have to filter out any 0 vectors after the fact, which would mean that the workers would have to know which vectors were bad, which means another synchronization problem... going to stick with this for now :)

**Comment by peterldowns** [comment]
^ Thank you!
