### ISSUE TITLE
Edge case: different metrics when creating and using

### ISSUE THREAD

**Issue by gregsadetsky** [spotify/annoy#285]
Hi,

Congratulations and thanks on the fantastic library! It's quite useful & fast (we use it for image matching, storing/querying vectors of image features).

I came upon an edge case. It may be "too" edge case / strange to matter, but just in case:

```
from annoy import AnnoyIndex

VECTOR_LENGTH = 1
NMB_TREES = 1

t = AnnoyIndex(VECTOR_LENGTH, metric='euclidean')
t.add_item(0, [0.4])
t.add_item(1, [0.4])
t.build(NMB_TREES)
t.save('test.ann')

# this will work
u = AnnoyIndex(VECTOR_LENGTH, metric='euclidean')
u.load('test.ann')
print(u.get_nns_by_item(0, 1))

# this will raise 'Item index larger than the largest item index'
# notice the different metric
v = AnnoyIndex(VECTOR_LENGTH, metric='angular')
v.load('test.ann')
print(v.get_nns_by_item(0, 1))
```

A few findings about this:
- the problem goes away if indices 1 and 2 are used instead of 0 and 1.
- the problem appears when the index is created as `euclidean` but queried as `angular`; not the other way around

---

I came upon this when opening a small ~40Mb annoy index (1M entries, all 1-item vectors -- it's a special case) and forgetting to pass 'euclidean' to use the Annoy index. I kept getting `Segmentation fault: 11` errors, which led me to 1) figure out why I was wrong (not passing the right metric) :-) 2) this edge case demonstration.

Cheers!

**Comment by erikbern** [comment]
Yeah, this will lead to all kinds of undefined behavior unfortunately.

In retrospect I wish I had defined the binary format in a different way... there's no place for "metadata" right now. So unfortunately this bug is pretty much "unsolvable" until I redefine the format. I think however it's possible to catch many common errors (eg if the index size is not an multiple of the vector size)

**Comment by gregsadetsky** [comment]
Thanks you for your answer! So then ok to close this?

**Comment by erikbern** [comment]
yeah probably worth closing for now

**Comment by a1k0n** [comment]
I'm guessing this is because the leaf node is defined to be the same size in bytes as a split vector, and there isn't room to actually store any leaves in the 1d case?

Luckily, 1-dimensional spaces are very easy to search without Annoy :)

**Comment by erikbern** [comment]
not sure I follow you @a1k0n – euclidean takes a bit more memory since you need to store the split offset

**Comment by a1k0n** [comment]
Oh, right, never mind!

I misremembered how the structure is laid out in memory -- i thought you had multiple vectors stored in leaves, but I can see it's only one where instead of the split plane it's the leaf node's vector. And yeah, there's a different node size for euclidean vs. angular because of the extra split offset.

**Comment by erikbern** [comment]
Anyway there's a few checks you can do that have no false positives but sometimes false negatives. 

For instance on this line we're computing the number of nodes: https://github.com/spotify/annoy/blob/master/src/annoylib.h#L690

`    _n_nodes = (S)(size / _s);`

This should always be a multiple, or else something is really weird
