### ISSUE TITLE
question about add_item start item number

### ISSUE THREAD

**Issue by goodloop** [spotify/annoy#295]
I use primary index number directly from my db  as `item` to annoy. So my code may as below
```
annoy = AnnoyIndex(100)
annoy.add_item( 10000, features_10000)
annoy.add_item( 10001, features_10001)
annoy.add_item( 10002, features_10002)
annoy.add_item( 10003, features_10003)
...
...
annoy.build(100)
annoy.get_nns_by_item(10000, 10)
```

seems the result  is not so good.

but if I change item number from 1. i.e.
```
annoy = AnnoyIndex(100)
annoy.add_item( 1, features_10000)
annoy.add_item( 2, features_10001)
annoy.add_item( 3, features_10002)
annoy.add_item( 4, features_10003)
...
...
annoy.build(100)
annoy.get_nns_by_item(1, 10)
```
this result get much much better. 
Is that make sense?

**Comment by goodloop** [comment]
in my test , I added about 15 items into index.   build(n_trees)  n_trees set to 10.
the first version only return 2 results, the second version can return more results with proper order.

does this give any hints?

**Comment by threehundred** [comment]
I'm getting the exact same problem as @goodloop.

Only two results returned when using database keys (i.e. large ints no starting at zero) . Everything is fine when using your example code though.

**Comment by erikbern** [comment]
Which version are you using? Did you install it from pypi or are you using the version in git?

There are some minor bugs fixed in the git repo that I haven't yet pushed to pypi, that have to do with "missing" items.

Btw @threehundred  it's not recommended to use arbitrary integers for ids – the index will still allocate memory assuming all ids are 0 ... max(id)-1. If you insert an item with id 1,000,000 then it will allocate space for 1M vectors

**Comment by goodloop** [comment]
I am using pypi version. I'll try git repo later.

**Comment by erikbern** [comment]
This looks broken still in latest master. Will look at it later.

**Comment by erikbern** [comment]
Closing this, will continue the conversation on #298
