### ISSUE TITLE
Feature Request: Index building directly from vector data serialized on disk.

### ISSUE THREAD

**Issue by windowpane** [spotify/annoy#333]
Hello,

*Request:* Feature which enables building the tree from data stored temporally on disk, in order to support construction of massive data sets (+1B rows) that don't fit entirely into memory.

Rather than store all vectors in memory to build the index, build the index from serialized vectors on disk.

*Known Drawbacks:* There would inevitable be some speed trade-off in construction time of the index, but for very large datasets there is no other way around it!

*Reasoning*: I've looked everywhere, no other solutions seem to offer a scalable solution that can build the index from disk if you have limited RAM. All other solutions i've seen are in memory, and database solutions appear non-existent for higher dimension (+8D) knn search. 

Annoy appears to be the project that would be most suitable for adding this feature, as it already has mem-mapping implemented.

Example use case:
```
# Length of item vector 128dimension with fixed leaf size
# and temporary file path specifying that data is written to disk before building
f = 128
t = AnnoyIndex(f, leaf_size = 1000, temp_file='raw_vectors.h5py)  

for i in xrange(int(1*1e9)):
    v = [random.gauss(0, 1) for z in xrange(f)]
    t.add_item(i, v)  # will be written to disk before index is built

t.build_and_save(10, 'test.ann') # 10 trees built using the serialized data and written directly to disk.
```

some perks:
  - able to scale to  +billions of rows by enabling:
    - massive single node storage using disk space
    - replicated storage of the index on multiple data nodes
   - cheapest way to scale (disk space is cheap compared to RAM)

Questions:
  - At what point would it be useful to integrate the c++ code as a plug for a database system like solr, elasticsearch, mongo or cassandra?
  - is it possible to represent the tree using dictionairy objects in python where the leaves are numpy/dask arrays in order to leverage the existing features of nosql document stores?

**Comment by erikbern** [comment]
Annoy isn't really built for out-of-memory nearest neighbor search. Despite the capabilities to do mmap, it still needs fairly quick random access to the underlying vectors. The mmap functionality is good for (a) sharing indexes across multiple process (since every process that opens the index uses the same memory) (b) fast loading of indexes.

So I think what you're asking for is a bit out of scope for what Annoy does right now.

I do agree that at some point it would be really cool if some "real" database would offer index support for nearest neighbors, and I wouldn't be surprised if we see that in the (near?) future since nearest neighbor search is becoming increasingly important.

For your particular use case maybe one option is to do clustering as a preprocessing technique to get the number of items down from 1B+ to say 10M. Then put the cluster centroids into Annoy. Just a random idea.

Closing this now since it seems unlikely Annoy will ever implement this but feel free to continue the conversation.
