### ISSUE TITLE
Why distance has the same type as vector elements in c++?

### ISSUE THREAD

**Issue by ibendrup** [spotify/annoy#351]
To save memory it would be useful to store vector elements in such types like `uint16_t `or `uint8_t`. But using such types to store distance value leads to significant accuracy loss. I think it makes sence always use `float`  to store distance values.

**Comment by ReneHollander** [comment]
I tried to separate the distance type from the type of the vectors, but the resulting reduction of memory usage was not that impressive. It only reduced the amount of memory needed by like 10% (maybe 20, but I am not so sure what it was...) with data that was stored as uint8_t instead of float. I think casting the values was having a performance impact as well, because the distance is calculated so often, that a cast from int to float got noticeable. There are also handcrafted AVX and SSE optimizations that rely on the data being floats (which I think is most likely due to Python only relying on an index which uses floats) which further help with performance.
