### ISSUE TITLE
Can't use the dot metric

### ISSUE THREAD

**Issue by alejandrojcastaneira** [spotify/annoy#357]
I tried to use the metric = "dot"  whit the latest version of annoy 1.15.0 and didn't work.

I installed from pip and also from the git-hub repo.

Best regards.

**Comment by erikbern** [comment]
Can you share a reproducible error?

**Comment by moshest** [comment]
I had also a problem with the dot metric.
The problem was saving the index with `"dot"` metric and load it with the default metric.

**Comment by shelbywhite** [comment]
"dot" metric isn't working for me either.

@erikbern  perhaps including a sample in the documentation for how to specifically use "dot" metric would be helpful if it's not the same as in the documentation... it really should work the same and so far I am still looking at my code as the issue. So I'll walk through my steps.

I've started with building a gensim word2vec model, normalizing the vectors (tried also without doing this), saving the model to disk with `metric="dot"`, loading the model from disk, then querying it with both `model.get_nns_by_vector()` and `model.get_nns_by_id()` both result in the program just exiting without an error. This does not happen when using `euclidean` distance. 

Now, in my vector output I am seeing negative numbers, which doesn't seem like normalization to me... and based on the documentation, it says the following: 
> a.add_item(i, v) adds item i (any nonnegative integer) with vector v...

**Could negative vector values be a reason why dot distance is not working?** There is no error, the program just exits. I also don't believe it's an error in the code as I can use `euclidean` distance perfectly fine with no changes to the code.

**Comment by erikbern** [comment]
@shelbywhite can you share code that triggers the error?

**Comment by shelbywhite** [comment]
@erikbern removed my comment as I found the issue to be malformed data coming from the Word2vec implementation. Happy to remove this comment as well to keep this issue clean & closed.

**Comment by erikbern** [comment]
It’s still not ideal that annoy crashes. In what way was the data malformed? It would be great to fix annoy so it raises an exception instead

**Comment by shelbywhite** [comment]
You're totally right—I'll explain. My input data was missing a vector; that may or may not have been an issue, but... The main issue was that during _creation_ of the index, the `metric` was set, however it wasn't set to the same value as when _loading_ the index.

However, there was no error letting me know that. I ran into this problem but didn't see it because my system generates a "state" of the model and saves it to JSON. I do this to always load the newest model, but also to save information about the model: "metric", "dims", "timestamp", etc. Within this JSON, "metric" was set properly from when the model was built, but in my actual AnnoyManager class the metric was hard coded as "euclidean". They didn't match up, so the model didn't load. 

That said, I think the question here is do you want to display an error when `metric` is not the same as the model itself? Or, when the distance calculation happens and it can't compute? Though, I'm pretty sure I saw you mention that the model doesn't contain that info.

**Comment by erikbern** [comment]
> You're totally right—I'll explain. My input data was missing a vector; that may or may not have been an issue, but... The main issue was that during _creation_ of the index, the `metric` was set, however it wasn't set to the same value as when _loading_ the index.

Interesting. It would be great if we don't crash in this case. Let me see if I can add a check for it.
