### ISSUE TITLE
Fail to build with large datasets

### ISSUE THREAD

**Issue by JanakaSandaruwan** [spotify/annoy#526]
I used annoy to build an index for 2 million vectors of size 1024. 

```
f = 1024
t = AnnoyIndex(f, 'euclidean')
t.on_disk_build('test.ann')

 '''code for adding 2 million vectors'''

t.build(25)
```
After adding vectors, t.build(25) runs forever. ( I let it to run about six hours and it doesn't finish)
The code works fine with 1 million vectors.

**Comment by erikbern** [comment]
You're probably running into memory limits with your machine. 2M vectors of size 1024 is already 8 GB and that's before you start adding indexes

**Comment by JanakaSandaruwan** [comment]
No. It runs up to t.build(25). Adding 2M vectors can be done without any issue. The issue is that t.build(25) is running for hours without finising.

**Comment by erikbern** [comment]
Yeah probably what happens is you're hitting the memory limit at some point. Try to run with `.verbose(True)` and you might see that the first few trees are relatively quick to add and then it gets slower at some point. That's because you're starting to swap to disk.

You might not need 25 trees btw, might be fine to try to a lower number.

**Comment by JanakaSandaruwan** [comment]
I tried with .verbose(True). The output shows just two lines as follows.
```
pass 0...
pass 0...
```
