### ISSUE TITLE
Distance of several nearest neighbors 0.0?

### ISSUE THREAD

**Issue by beichenc** [spotify/annoy#555]
I am using get_nns_by_vector with return_distances=True, and after checking the distance vector I see that often there are many nearest neighbors all having distance 0.0. It makes sense that the first one is 0.0 since it found itself, but why is the second, third, etc. also 0.0? I have seen cases where I obtain 0.0 for the first 14 nearest neighbors.

Does this mean, that all the nearest neighbors with distance 0.0 are actually one and the same sample - itself? Or has it actually found different samples that are very close in distance?

**Comment by erikbern** [comment]
What should the distances be? Are they close enough to zero that it might be a rounding issue?

**Comment by beichenc** [comment]
I have made some checks by printing the nearest neighbor vectors of cases when distance is 0.0. The vectors returned (i.e. all first 14 nearest neighbors as described above) are all exactly the same as the self vector.

**Comment by erikbern** [comment]
What are their true distances though?

**Comment by AdityaSoni19031997** [comment]
Didn't want to start a new issue, so leaving my query here! 

First of all, thanks for a great package, slides and the paper! What i was wondering is how should one go about selecting the best approximated item by annoy? Like at what threshold should one cut-off the top-k? Is there a better way to do it rather than using intuitions?

e.g. annoy can return anything b/w 0-2 when we use cosine as the metric, since less is better, but how much less is what i want to find out!

Be Safe,
Thanks!

**Comment by erikbern** [comment]
Just use the top k neighbors would be one approach. That way you don't have to pick a distance threshold
